// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPa9xaV3mo3L_hkkphcqOA2yHVdshzECA',
    appId: '1:303957346363:web:d2756d5f531e8c3f7db41e',
    messagingSenderId: '303957346363',
    projectId: 'talkr-1d1a6',
    authDomain: 'talkr-1d1a6.firebaseapp.com',
    storageBucket: 'talkr-1d1a6.appspot.com',
    measurementId: 'G-61E9B9EW0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzL9uEa5QSq3N6ovO1NxJRcJXCVP_XPxI',
    appId: '1:303957346363:android:c27ea7b507db1b137db41e',
    messagingSenderId: '303957346363',
    projectId: 'talkr-1d1a6',
    storageBucket: 'talkr-1d1a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv743Xy6wCDEbuqSX1bjLa7JlBjZUY8go',
    appId: '1:303957346363:ios:a22c780a94bcb88a7db41e',
    messagingSenderId: '303957346363',
    projectId: 'talkr-1d1a6',
    storageBucket: 'talkr-1d1a6.appspot.com',
    iosBundleId: 'com.example.talkr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv743Xy6wCDEbuqSX1bjLa7JlBjZUY8go',
    appId: '1:303957346363:ios:4563bf2003ddfe937db41e',
    messagingSenderId: '303957346363',
    projectId: 'talkr-1d1a6',
    storageBucket: 'talkr-1d1a6.appspot.com',
    iosBundleId: 'com.example.talkr.RunnerTests',
  );
}
